version: '3.7'

services:
  main:
    container_name: governance-data-bot
    build: ./
    restart: always
    environment:
      - PORT=3000
    env_file:
      - .env
    ports:
      - '3000:3000'
